import { Template, SubscriptionPlan } from '../types';

export const MOCK_TEMPLATES: Template[] = [
  // ─── Featured ──────────────────────────────────────────────────────────────
  {
    id: 'featured-1',
    title: 'Baby Banana',
    category: 'Featured',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/baby_banana_xsrbzp.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772369987/baby_banana_xsrbzp.mp4',
    localVideo: require('../videos/baby_banana.mp4'),
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isFeatured: true,
    isPopular: true,
  },

  {
    id: 'featured-2',
    title: 'Cute Baby',
    category: 'Featured',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/cute_baby_fxcr4u.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772375802/cute_baby_fxcr4u.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isFeatured: true,
    isPopular: true,
  },

  // ─── Trend Videos ──────────────────────────────────────────────────────────
  {
    id: 'tv-1',
    title: 'Dance Challenge',
    category: 'Trend Videos',
    thumbnailUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&q=80',
    videoUrl: '',
    duration: 30,
    credits: 800,
    hasSound: true,
    characterCount: 2,
    isTrending: true,
    tags: ['#DanceChallenge', '#Viral'],
  },
  {
    id: 'tv-2',
    title: 'Fantasy World',
    category: 'Trend Videos',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&q=80',
    videoUrl: '',
    duration: 35,
    credits: 900,
    hasSound: true,
    characterCount: 2,
    isTrending: true,
    tags: ['#Fantasy', '#AI'],
  },
  {
    id: 'tv-3',
    title: 'Urban Beat',
    category: 'Trend Videos',
    thumbnailUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&q=80',
    videoUrl: '',
    duration: 25,
    credits: 750,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
    tags: ['#Urban', '#Trending'],
  },

  // ─── Viral Dance ────────────────────────────────────────────────────────────
  {
    id: 'vd-1',
    title: 'Great Woman',
    category: 'Viral Dance',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/indir_1_zuoiyf.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772925740/indir_1_zuoiyf.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'vd-2',
    title: 'Trump',
    category: 'Viral Dance',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/indir_tpo8j2.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772925740/indir_tpo8j2.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'vd-3',
    title: 'Happy Chinese',
    category: 'Viral Dance',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/Happy_Chinese_New_Year_txq8hb.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772925740/Happy_Chinese_New_Year_txq8hb.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'vd-4',
    title: 'My Popopo',
    category: 'Viral Dance',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/My_popopo_Lara_Shalala_Created_by_KlingAI_X-_challenge_alflld.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772925742/My_popopo_Lara_Shalala_Created_by_KlingAI_X-_challenge_alflld.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'vd-5',
    title: 'God Of War',
    category: 'Viral Dance',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/God_of_War_does_dance_leaves_the_battlefield_and_moves_to_the_beat_raw_power_cinematic_presence_unstoppable_energy._Created_by_KlingAI_X-_bxt64n.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772925743/God_of_War_does_dance_leaves_the_battlefield_and_moves_to_the_beat_raw_power_cinematic_presence_unstoppable_energy._Created_by_KlingAI_X-_bxt64n.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'vd-6',
    title: 'Jin Kazama',
    category: 'Viral Dance',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/Jin_Kazama_doing_the_SHINY_dance_eulpxs.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772925742/Jin_Kazama_doing_the_SHINY_dance_eulpxs.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'vd-8',
    title: 'Mon Shake',
    category: 'Viral Dance',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/C_mon_Shake_it_Shake_it_mashup_by_vby47i.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772925742/C_mon_Shake_it_Shake_it_mashup_by_vby47i.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'vd-7',
    title: 'Hm Man',
    category: 'Viral Dance',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/hm.touhidul_-_7605996373019872532_srdvia.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772925741/hm.touhidul_-_7605996373019872532_srdvia.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },

  // ─── Baby Kids ─────────────────────────────────────────────────────────────
  {
    id: 'bk-1',
    title: 'Pink Baby',
    category: 'Baby Kids',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/pink_baby_igsjyp.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772397812/pink_baby_igsjyp.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'bk-2',
    title: 'Cute Baby Dancing',
    category: 'Baby Kids',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/Cute_baby_dancing_rcwvnn.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772397689/Cute_baby_dancing_rcwvnn.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'bk-3',
    title: 'Cute Baby Cool Dance',
    category: 'Baby Kids',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/Cute_baby_cool_dance_vpis4s.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772397688/Cute_baby_cool_dance_vpis4s.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'bk-4',
    title: 'Aló Mama',
    category: 'Baby Kids',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/Al%C3%B3_Mama_u3xsxk.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772397687/Al%C3%B3_Mama_u3xsxk.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'bk-5',
    title: 'Black Baby',
    category: 'Baby Kids',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/black_baby_byeuts.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772397687/black_baby_byeuts.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'bk-6',
    title: 'AI Baby Chatter',
    category: 'Baby Kids',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/Cute_AI_Baby_Chatter_Baby_Talk_Humor_AI_Babies_Gone_Viral._.._n8yamf.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772397687/Cute_AI_Baby_Chatter_Baby_Talk_Humor_AI_Babies_Gone_Viral._.._n8yamf.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'bk-7',
    title: 'Police Baby',
    category: 'Baby Kids',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/police_baby_dfvqpi.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772397686/police_baby_dfvqpi.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'bk-8',
    title: 'Chloe Kids AI',
    category: 'Baby Kids',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/chloekidsai_-_7529131869183495446_f7bgvi.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772397686/chloekidsai_-_7529131869183495446_f7bgvi.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'bk-9',
    title: 'Blue Baby',
    category: 'Baby Kids',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/blue_baby_cndzcc.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772923929/blue_baby_cndzcc.mov',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'bk-10',
    title: 'Microphone Baby',
    category: 'Baby Kids',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/microphone_baby_dbtucc.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772923924/microphone_baby_dbtucc.mov',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'bk-11',
    title: 'Yellow Baby',
    category: 'Baby Kids',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/yellow_baby_v0r8m2.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772923923/yellow_baby_v0r8m2.mov',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'bk-12',
    title: 'Cow Baby',
    category: 'Baby Kids',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/cow_baby_tyllmq.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772923923/cow_baby_tyllmq.mov',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },

  // ─── Kids Dance ────────────────────────────────────────────────────────────
  {
    id: 'kd-1',
    title: 'Hip Hop Kid',
    category: 'Kids Dance',
    thumbnailUrl: 'https://images.unsplash.com/photo-1619118536038-23f9e3f4b09e?w=400&q=80',
    videoUrl: '',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'kd-2',
    title: 'Ballet Dreams',
    category: 'Kids Dance',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=400&q=80',
    videoUrl: '',
    duration: 20,
    credits: 600,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'kd-3',
    title: 'Street Moves',
    category: 'Kids Dance',
    thumbnailUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&q=80',
    videoUrl: '',
    duration: 18,
    credits: 550,
    hasSound: true,
    characterCount: 1,
  },

  // ─── Popular Now ────────────────────────────────────────────────────────────
  {
    id: 'pn-1',
    title: 'Army Dreamers',
    category: 'Popular Now',
    thumbnailUrl: 'https://images.unsplash.com/photo-1578070181910-f1e514afdd08?w=400&q=80',
    videoUrl: '',
    duration: 30,
    credits: 800,
    hasSound: true,
    characterCount: 2,
    isPopular: true,
    characters: [
      { id: 'c1', thumbnailUrl: 'https://i.pravatar.cc/80?img=1' },
      { id: 'c2', thumbnailUrl: 'https://i.pravatar.cc/80?img=2' },
      { id: 'c3', thumbnailUrl: 'https://i.pravatar.cc/80?img=3' },
      { id: 'c4', thumbnailUrl: 'https://i.pravatar.cc/80?img=4' },
      { id: 'c5', thumbnailUrl: 'https://i.pravatar.cc/80?img=5' },
    ],
  },
  {
    id: 'pn-2',
    title: 'Neon Anime',
    category: 'Popular Now',
    thumbnailUrl: 'https://images.unsplash.com/photo-1614028674026-a65e31bfd27c?w=400&q=80',
    videoUrl: '',
    duration: 25,
    credits: 700,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'pn-3',
    title: 'Couples Dance',
    category: 'Popular Now',
    thumbnailUrl: 'https://images.unsplash.com/photo-1504609813442-a8924e83f76e?w=400&q=80',
    videoUrl: '',
    duration: 28,
    credits: 750,
    hasSound: true,
    characterCount: 2,
    isPopular: true,
  },

  // ─── All Eyes On You ────────────────────────────────────────────────────────
  {
    id: 'ae-1',
    title: 'Diva Walk',
    category: 'All Eyes On You',
    thumbnailUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&q=80',
    videoUrl: '',
    duration: 20,
    credits: 700,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'ae-2',
    title: 'Red Carpet',
    category: 'All Eyes On You',
    thumbnailUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&q=80',
    videoUrl: '',
    duration: 25,
    credits: 750,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'ae-3',
    title: 'Spotlight',
    category: 'All Eyes On You',
    thumbnailUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&q=80',
    videoUrl: '',
    duration: 22,
    credits: 720,
    hasSound: true,
    characterCount: 1,
  },

  // ─── Cartoon ────────────────────────────────────────────────────────────────
  {
    id: 'ct-1',
    title: 'Red Woman',
    category: 'Cartoon',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1772926413/AI_3_wwrqgy.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772926413/AI_3_wwrqgy.mov',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'ct-2',
    title: 'White Woman',
    category: 'Cartoon',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1772926418/AI_tbydx2.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772926418/AI_tbydx2.mov',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'ct-3',
    title: 'Ai China',
    category: 'Cartoon',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1772926407/AI_4_ddaiin.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772926407/AI_4_ddaiin.mov',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'ct-4',
    title: 'Funny',
    category: 'Cartoon',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1772926407/AI_5_mgl2iz.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772926407/AI_5_mgl2iz.mov',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'ct-5',
    title: 'Funny Men',
    category: 'Cartoon',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1772926407/AI_j2u01k.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772926407/AI_j2u01k.mov',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'ct-6',
    title: 'Great Woman',
    category: 'Cartoon',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1772926403/AI_1_eykkrp.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772926403/AI_1_eykkrp.mov',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
];

export const TEMPLATE_CATEGORIES = [
  'Featured',
  'Baby Kids',
  'Trend Videos',
  'Viral Dance',
  'Kids Dance',
  'Popular Now',
  'All Eyes On You',
  'Cartoon',
];

export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'weekly_3000',
    name: 'Diamond Unlimited',
    credits: 3000,
    priceDisplay: '₺449,99',
    period: 'Hafta',
    trialDays: 3,
    features: [
      'Unlimited AI video generation',
      '3000 credits per week',
      'Priority processing',
      'HD video quality',
      'No watermark',
    ],
  },
];

export const getTemplateById = (id: string): Template | undefined =>
  MOCK_TEMPLATES.find((t) => t.id === id);

export const getTemplatesByCategory = (category: string): Template[] =>
  MOCK_TEMPLATES.filter((t) => t.category === category);
