import { Template, SubscriptionPlan } from '../types';

export const MOCK_TEMPLATES: Template[] = [
  // ─── Featured ──────────────────────────────────────────────────────────────
  {
    id: 'featured-1',
    title: 'Baby Banana',
    category: 'Featured',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/baby_banana_xsrbzp.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772369987/baby_banana_xsrbzp.mp4',
    localVideo: require('../videos/baby_banana.mp4'),
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isFeatured: true,
    isPopular: true,
  },
  {
    id: 'featured-2',
    title: 'The Money Dady',
    category: 'Featured',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773260300/The_Money_Dance_Man_In_Money_Print_Hoodie_Rapping_Gold_Chains_AI_Video_zqftyp.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773260300/The_Money_Dance_Man_In_Money_Print_Hoodie_Rapping_Gold_Chains_AI_Video_zqftyp.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isFeatured: true,
    isPopular: true,
  },
  {
    id: 'featured-3',
    title: 'My Popopo',
    category: 'Featured',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1772925742/My_popopo_Lara_Shalala_Created_by_KlingAI_X-_challenge_alflld.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772925742/My_popopo_Lara_Shalala_Created_by_KlingAI_X-_challenge_alflld.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isFeatured: true,
    isPopular: true,
  },
  {
    id: 'featured-4',
    title: 'Blonde Woman',
    category: 'Featured',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773260758/Blonde_Woman_In_Red_Sweater_And_White_Fur_Hat_In_Snowy_Scene_AI_Video_r4dich.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773260758/Blonde_Woman_In_Red_Sweater_And_White_Fur_Hat_In_Snowy_Scene_AI_Video_r4dich.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isFeatured: true,
  },
  {
    id: 'featured-5',
    title: 'Red Man',
    category: 'Featured',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773260742/red_man_pd5thp.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773260742/red_man_pd5thp.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isFeatured: true,
  },
  {
    id: 'featured-6',
    title: 'Red Haired',
    category: 'Featured',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773260291/Red_Haired_Girl_In_White_Puffer_Jacket_And_Pink_Polka_Dot_Shirt_AI_Video_nckksa.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773260291/Red_Haired_Girl_In_White_Puffer_Jacket_And_Pink_Polka_Dot_Shirt_AI_Video_nckksa.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isFeatured: true,
  },
  {
    id: 'featured-7',
    title: 'Cute Baby',
    category: 'Featured',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/cute_baby_fxcr4u.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772375802/cute_baby_fxcr4u.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isFeatured: true,
    isPopular: true,
  },
  {
    id: 'featured-8',
    title: 'Child Ai',
    category: 'Featured',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1772926407/AI_j2u01k.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772926407/AI_j2u01k.mov',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isFeatured: true,
  },
  {
    id: 'featured-9',
    title: 'A Woman',
    category: 'Featured',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773259930/A_Woman_Walks_Calmly_Towards_The_Camera_Smiling_Softly_Natural_Light_Rich_Detail_AI_Video_fxqdwf.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773259930/A_Woman_Walks_Calmly_Towards_The_Camera_Smiling_Softly_Natural_Light_Rich_Detail_AI_Video_fxqdwf.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isFeatured: true,
  },
  {
    id: 'featured-10',
    title: 'Glass Men',
    category: 'Featured',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773259943/Glass_men_Gen_AI_Video_AI_Image_Generator_su54hv.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773259943/Glass_men_Gen_AI_Video_AI_Image_Generator_su54hv.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isFeatured: true,
  },

  // ─── Trend Videos ──────────────────────────────────────────────────────────
  {
    id: 'tv-1',
    title: 'Glass Men',
    category: 'Trend Videos',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773259943/Glass_men_Gen_AI_Video_AI_Image_Generator_su54hv.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773259943/Glass_men_Gen_AI_Video_AI_Image_Generator_su54hv.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'tv-2',
    title: 'Orange Woman',
    category: 'Trend Videos',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773259937/orange_woman_lmt9b1.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773259937/orange_woman_lmt9b1.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'tv-3',
    title: 'A Woman',
    category: 'Trend Videos',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773259930/A_Woman_Walks_Calmly_Towards_The_Camera_Smiling_Softly_Natural_Light_Rich_Detail_AI_Video_fxqdwf.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773259930/A_Woman_Walks_Calmly_Towards_The_Camera_Smiling_Softly_Natural_Light_Rich_Detail_AI_Video_fxqdwf.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'tv-4',
    title: 'Superman',
    category: 'Trend Videos',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773259938/Superman_Flying_Over_Cityscape_At_Sunset_Superhero_Action_Scene_AI_Video_jzkaex.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773259938/Superman_Flying_Over_Cityscape_At_Sunset_Superhero_Action_Scene_AI_Video_jzkaex.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'tv-5',
    title: 'A Woman Smiling',
    category: 'Trend Videos',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773259934/A_Woman_Slowly_Walking_Towards_The_Camera_Smiling_Natural_Light_Rich_Detail_AI_Video_vz78l4.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773259934/A_Woman_Slowly_Walking_Towards_The_Camera_Smiling_Natural_Light_Rich_Detail_AI_Video_vz78l4.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'tv-6',
    title: 'Man in Baseball',
    category: 'Trend Videos',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773259935/Man_In_Baseball_Cap_Standing_In_Foggy_Forest_Zoom_In_Out_Effect_AI_Video_exk98t.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773259935/Man_In_Baseball_Cap_Standing_In_Foggy_Forest_Zoom_In_Out_Effect_AI_Video_exk98t.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'tv-7',
    title: 'Transform',
    category: 'Trend Videos',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773259950/Transform_Kamen_Rider_Pepsi_Superhero_In_City_Street_AI_Video_mofhkw.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773259950/Transform_Kamen_Rider_Pepsi_Superhero_In_City_Street_AI_Video_mofhkw.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'tv-8',
    title: 'Unique Style',
    category: 'Trend Videos',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773259960/Unique_Style_Woman_With_Peacock_Feather_And_Heart_Earrings_AI_Video_qei1xs.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773259960/Unique_Style_Woman_With_Peacock_Feather_And_Heart_Earrings_AI_Video_qei1xs.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'tv-9',
    title: 'Futuristic Style',
    category: 'Trend Videos',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773259973/Futuristic_Style_Character_Performs_Precise_Movements_With_Car_And_Drones_AI_Video_gpuj08.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773259973/Futuristic_Style_Character_Performs_Precise_Movements_With_Car_And_Drones_AI_Video_gpuj08.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'tv-10',
    title: 'Baby Ai Gen',
    category: 'Trend Videos',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773259958/baby_ai_gen_mmje0a.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773259958/baby_ai_gen_mmje0a.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },

  // ─── Viral Dance ────────────────────────────────────────────────────────────
  {
    id: 'vd-1',
    title: 'Great Woman',
    category: 'Viral Dance',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/indir_1_zuoiyf.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772925740/indir_1_zuoiyf.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'vd-2',
    title: 'Trump',
    category: 'Viral Dance',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/indir_tpo8j2.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772925740/indir_tpo8j2.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'vd-3',
    title: 'Happy Chinese',
    category: 'Viral Dance',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/Happy_Chinese_New_Year_txq8hb.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772925740/Happy_Chinese_New_Year_txq8hb.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'vd-4',
    title: 'My Popopo',
    category: 'Viral Dance',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/My_popopo_Lara_Shalala_Created_by_KlingAI_X-_challenge_alflld.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772925742/My_popopo_Lara_Shalala_Created_by_KlingAI_X-_challenge_alflld.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'vd-5',
    title: 'God Of War',
    category: 'Viral Dance',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/God_of_War_does_dance_leaves_the_battlefield_and_moves_to_the_beat_raw_power_cinematic_presence_unstoppable_energy._Created_by_KlingAI_X-_bxt64n.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772925743/God_of_War_does_dance_leaves_the_battlefield_and_moves_to_the_beat_raw_power_cinematic_presence_unstoppable_energy._Created_by_KlingAI_X-_bxt64n.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'vd-6',
    title: 'Jin Kazama',
    category: 'Viral Dance',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/Jin_Kazama_doing_the_SHINY_dance_eulpxs.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772925742/Jin_Kazama_doing_the_SHINY_dance_eulpxs.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'vd-8',
    title: 'Mon Shake',
    category: 'Viral Dance',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/C_mon_Shake_it_Shake_it_mashup_by_vby47i.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772925742/C_mon_Shake_it_Shake_it_mashup_by_vby47i.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'vd-7',
    title: 'Hm Man',
    category: 'Viral Dance',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/hm.touhidul_-_7605996373019872532_srdvia.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772925741/hm.touhidul_-_7605996373019872532_srdvia.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },

  // ─── Baby Kids ─────────────────────────────────────────────────────────────
  {
    id: 'bk-1',
    title: 'Pink Baby',
    category: 'Baby Kids',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/pink_baby_igsjyp.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772397812/pink_baby_igsjyp.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'bk-2',
    title: 'Cute Baby Dancing',
    category: 'Baby Kids',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/Cute_baby_dancing_rcwvnn.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772397689/Cute_baby_dancing_rcwvnn.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'bk-3',
    title: 'Cute Baby Cool Dance',
    category: 'Baby Kids',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/Cute_baby_cool_dance_vpis4s.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772397688/Cute_baby_cool_dance_vpis4s.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'bk-4',
    title: 'Aló Mama',
    category: 'Baby Kids',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/Al%C3%B3_Mama_u3xsxk.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772397687/Al%C3%B3_Mama_u3xsxk.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'bk-5',
    title: 'Black Baby',
    category: 'Baby Kids',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/black_baby_byeuts.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772397687/black_baby_byeuts.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'bk-6',
    title: 'AI Baby Chatter',
    category: 'Baby Kids',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/Cute_AI_Baby_Chatter_Baby_Talk_Humor_AI_Babies_Gone_Viral._.._n8yamf.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772397687/Cute_AI_Baby_Chatter_Baby_Talk_Humor_AI_Babies_Gone_Viral._.._n8yamf.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'bk-7',
    title: 'Police Baby',
    category: 'Baby Kids',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/police_baby_dfvqpi.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772397686/police_baby_dfvqpi.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'bk-8',
    title: 'Chloe Kids AI',
    category: 'Baby Kids',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/chloekidsai_-_7529131869183495446_f7bgvi.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772397686/chloekidsai_-_7529131869183495446_f7bgvi.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'bk-9',
    title: 'Blue Baby',
    category: 'Baby Kids',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/blue_baby_cndzcc.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772923929/blue_baby_cndzcc.mov',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'bk-10',
    title: 'Microphone Baby',
    category: 'Baby Kids',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/microphone_baby_dbtucc.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772923924/microphone_baby_dbtucc.mov',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'bk-11',
    title: 'Yellow Baby',
    category: 'Baby Kids',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/yellow_baby_v0r8m2.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772923923/yellow_baby_v0r8m2.mov',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'bk-12',
    title: 'Cow Baby',
    category: 'Baby Kids',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/cow_baby_tyllmq.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772923923/cow_baby_tyllmq.mov',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },

  // ─── Popular Now ────────────────────────────────────────────────────────────
  {
    id: 'pn-1',
    title: 'Man in Tuxedo',
    category: 'Popular Now',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773260272/Man_In_Tuxedo_Performing_Magic_Tricks_At_A_Luxury_Event_AI_Video_eipmta.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773260272/Man_In_Tuxedo_Performing_Magic_Tricks_At_A_Luxury_Event_AI_Video_eipmta.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'pn-2',
    title: 'Man in Blazer',
    category: 'Popular Now',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773260287/Man_In_Blazer_Standing_By_Pool_With_Autumn_Trees_In_Background_AI_Video_tq438k.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773260287/Man_In_Blazer_Standing_By_Pool_With_Autumn_Trees_In_Background_AI_Video_tq438k.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'pn-3',
    title: 'The Money',
    category: 'Popular Now',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773260300/The_Money_Dance_Man_In_Money_Print_Hoodie_Rapping_Gold_Chains_AI_Video_zqftyp.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773260300/The_Money_Dance_Man_In_Money_Print_Hoodie_Rapping_Gold_Chains_AI_Video_zqftyp.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'pn-4',
    title: 'Woman Posing',
    category: 'Popular Now',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773260289/Woman_Posing_In_Front_Of_A_Canyon_At_Sunset_AI_Video_ttvubg.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773260289/Woman_Posing_In_Front_Of_A_Canyon_At_Sunset_AI_Video_ttvubg.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'pn-5',
    title: 'Slow Motion',
    category: 'Popular Now',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773260284/Slow_Motion_360d_Man_Walking_Through_Rain_In_Urban_City_AI_Video_koj70h.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773260284/Slow_Motion_360d_Man_Walking_Through_Rain_In_Urban_City_AI_Video_koj70h.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'pn-6',
    title: 'Cartoon Style Baby',
    category: 'Popular Now',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773260283/cartoonstyle_baby_qjihzb.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773260283/cartoonstyle_baby_qjihzb.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'pn-7',
    title: 'Red Haired',
    category: 'Popular Now',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773260291/Red_Haired_Girl_In_White_Puffer_Jacket_And_Pink_Polka_Dot_Shirt_AI_Video_nckksa.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773260291/Red_Haired_Girl_In_White_Puffer_Jacket_And_Pink_Polka_Dot_Shirt_AI_Video_nckksa.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'pn-8',
    title: 'Sunset Girl',
    category: 'Popular Now',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773260311/sunset_girl_tjag5h.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773260311/sunset_girl_tjag5h.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'pn-9',
    title: 'Beautiful Woman',
    category: 'Popular Now',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773260302/Beautiful_Woman_Wearing_A_Beautiful_Pink_Dress_AI_Video_fsghtx.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773260302/Beautiful_Woman_Wearing_A_Beautiful_Pink_Dress_AI_Video_fsghtx.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'pn-10',
    title: 'Chinese Dance',
    category: 'Popular Now',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773260304/Chinese_Dance_Graceful_Movements_Traditional_Attire_Captivating_Performance_AI_Video_f2titp.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773260304/Chinese_Dance_Graceful_Movements_Traditional_Attire_Captivating_Performance_AI_Video_f2titp.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },

  // ─── All Eyes On You ────────────────────────────────────────────────────────
  {
    id: 'ae-1',
    title: 'Woman Gracefully',
    category: 'All Eyes On You',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773260748/Woman_Gracefully_Rises_From_Chair_Walks_Away_With_Smooth_Natural_Movements_AI_Video_udcnzj.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773260748/Woman_Gracefully_Rises_From_Chair_Walks_Away_With_Smooth_Natural_Movements_AI_Video_udcnzj.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'ae-2',
    title: 'Blonde Woman',
    category: 'All Eyes On You',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773260758/Blonde_Woman_In_Red_Sweater_And_White_Fur_Hat_In_Snowy_Scene_AI_Video_r4dich.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773260758/Blonde_Woman_In_Red_Sweater_And_White_Fur_Hat_In_Snowy_Scene_AI_Video_r4dich.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'ae-3',
    title: 'Young Man',
    category: 'All Eyes On You',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773260757/young_man_e9jihm.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773260757/young_man_e9jihm.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'ae-4',
    title: 'My Coworker',
    category: 'All Eyes On You',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773260748/My_Coworker_Dreamed_Of_Boxing_In_A_World_Championship_Ring_AI_Video_smd5n2.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773260748/My_Coworker_Dreamed_Of_Boxing_In_A_World_Championship_Ring_AI_Video_smd5n2.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'ae-5',
    title: 'Ultra Realistic',
    category: 'All Eyes On You',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773260749/Ultra_Realistic_Cinematic_Animation_Ballerina_Dramatic_Eye_Focus_Transition_AI_Video_uiaqei.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773260749/Ultra_Realistic_Cinematic_Animation_Ballerina_Dramatic_Eye_Focus_Transition_AI_Video_uiaqei.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'ae-6',
    title: 'Red Man',
    category: 'All Eyes On You',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773260742/red_man_pd5thp.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773260742/red_man_pd5thp.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'ae-7',
    title: 'Ai Fashion',
    category: 'All Eyes On You',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773260737/Ai_Fashion_Command_Stylish_Girl_In_Cafe_Setting_AI_Video_g1mm9e.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773260737/Ai_Fashion_Command_Stylish_Girl_In_Cafe_Setting_AI_Video_g1mm9e.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'ae-8',
    title: 'Next Gen AI',
    category: 'All Eyes On You',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773260761/Next-Gen_AI_Video_AI_Image_Generator_crnb69.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773260761/Next-Gen_AI_Video_AI_Image_Generator_crnb69.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'ae-9',
    title: 'Classic AI Woman',
    category: 'All Eyes On You',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773260751/Classic_ai_woman_o3nauo.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773260751/Classic_ai_woman_o3nauo.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'ae-10',
    title: 'Cheenese Girl',
    category: 'All Eyes On You',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1773260766/Ggaggung_Dance_Kpop_Girl_In_Red_Hat_And_Striped_Sweater_AI_Video_eopdck.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1773260766/Ggaggung_Dance_Kpop_Girl_In_Red_Hat_And_Striped_Sweater_AI_Video_eopdck.mp4',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },

  // ─── Cartoon ────────────────────────────────────────────────────────────────
  {
    id: 'ct-1',
    title: 'Red Woman',
    category: 'Cartoon',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1772926413/AI_3_wwrqgy.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772926413/AI_3_wwrqgy.mov',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'ct-2',
    title: 'White Woman',
    category: 'Cartoon',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1772926418/AI_tbydx2.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772926418/AI_tbydx2.mov',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'ct-3',
    title: 'Ai China',
    category: 'Cartoon',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1772926407/AI_4_ddaiin.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772926407/AI_4_ddaiin.mov',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'ct-4',
    title: 'Funny',
    category: 'Cartoon',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1772926407/AI_5_mgl2iz.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772926407/AI_5_mgl2iz.mov',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'ct-5',
    title: 'Funny Men',
    category: 'Cartoon',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1772926407/AI_j2u01k.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772926407/AI_j2u01k.mov',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'ct-6',
    title: 'Great Woman',
    category: 'Cartoon',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/v1772926403/AI_1_eykkrp.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772926403/AI_1_eykkrp.mov',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
];

export const TEMPLATE_CATEGORIES = [
  'Featured',
  'Baby Kids',
  'Trend Videos',
  'Viral Dance',
  'Popular Now',
  'All Eyes On You',
  'Cartoon',
];

export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'weekly_3000',
    name: 'Diamond Unlimited',
    credits: 3000,
    priceDisplay: '₺449,99',
    period: 'Hafta',
    trialDays: 3,
    features: [
      'Unlimited AI video generation',
      '3000 credits per week',
      'Priority processing',
      'HD video quality',
      'No watermark',
    ],
  },
];

export const getTemplateById = (id: string): Template | undefined =>
  MOCK_TEMPLATES.find((t) => t.id === id);

export const getTemplatesByCategory = (category: string): Template[] =>
  MOCK_TEMPLATES.filter((t) => t.category === category);
