import { Template, SubscriptionPlan } from '../types';

export const MOCK_TEMPLATES: Template[] = [
  // ─── Featured ──────────────────────────────────────────────────────────────
  {
    id: 'featured-1',
    title: 'Baby Banana',
    category: 'Featured',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/baby_banana_xsrbzp.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772369987/baby_banana_xsrbzp.mp4',
    localVideo: require('../videos/baby_banana.mp4'),
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isFeatured: true,
    isPopular: true,
  },

  {
    id: 'featured-2',
    title: 'Cute Baby',
    category: 'Featured',
    thumbnailUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/so_0/cute_baby_fxcr4u.jpg',
    videoUrl: 'https://res.cloudinary.com/dpg9ld8n8/video/upload/v1772375802/cute_baby_fxcr4u.mp4',
    duration: 0,
    credits: 500,
    hasSound: true,
    characterCount: 1,
    isFeatured: true,
    isPopular: true,
  },

  // ─── Trend Videos ──────────────────────────────────────────────────────────
  {
    id: 'tv-1',
    title: 'Dance Challenge',
    category: 'Trend Videos',
    thumbnailUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&q=80',
    videoUrl: '',
    duration: 30,
    credits: 800,
    hasSound: true,
    characterCount: 2,
    isTrending: true,
    tags: ['#DanceChallenge', '#Viral'],
  },
  {
    id: 'tv-2',
    title: 'Fantasy World',
    category: 'Trend Videos',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&q=80',
    videoUrl: '',
    duration: 35,
    credits: 900,
    hasSound: true,
    characterCount: 2,
    isTrending: true,
    tags: ['#Fantasy', '#AI'],
  },
  {
    id: 'tv-3',
    title: 'Urban Beat',
    category: 'Trend Videos',
    thumbnailUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&q=80',
    videoUrl: '',
    duration: 25,
    credits: 750,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
    tags: ['#Urban', '#Trending'],
  },

  // ─── Viral Dance ────────────────────────────────────────────────────────────
  {
    id: 'vd-1',
    title: 'Viral Groove',
    category: 'Viral Dance',
    thumbnailUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&q=80',
    videoUrl: '',
    duration: 25,
    credits: 700,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
    tags: ['#ViralDance', '#Trending'],
  },
  {
    id: 'vd-2',
    title: 'TikTok Moves',
    category: 'Viral Dance',
    thumbnailUrl: 'https://images.unsplash.com/photo-1535525153412-5a42439a210d?w=400&q=80',
    videoUrl: '',
    duration: 20,
    credits: 650,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
    tags: ['#TikTok', '#Viral'],
  },
  {
    id: 'vd-3',
    title: 'Flash Mob',
    category: 'Viral Dance',
    thumbnailUrl: 'https://images.unsplash.com/photo-1547153760-18fc86324498?w=400&q=80',
    videoUrl: '',
    duration: 30,
    credits: 800,
    hasSound: true,
    characterCount: 3,
    isTrending: true,
    tags: ['#FlashMob', '#Viral'],
  },

  // ─── Kids Dance ────────────────────────────────────────────────────────────
  {
    id: 'kd-1',
    title: 'Hip Hop Kid',
    category: 'Kids Dance',
    thumbnailUrl: 'https://images.unsplash.com/photo-1619118536038-23f9e3f4b09e?w=400&q=80',
    videoUrl: '',
    duration: 15,
    credits: 500,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'kd-2',
    title: 'Ballet Dreams',
    category: 'Kids Dance',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=400&q=80',
    videoUrl: '',
    duration: 20,
    credits: 600,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'kd-3',
    title: 'Street Moves',
    category: 'Kids Dance',
    thumbnailUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&q=80',
    videoUrl: '',
    duration: 18,
    credits: 550,
    hasSound: true,
    characterCount: 1,
  },

  // ─── Popular Now ────────────────────────────────────────────────────────────
  {
    id: 'pn-1',
    title: 'Army Dreamers',
    category: 'Popular Now',
    thumbnailUrl: 'https://images.unsplash.com/photo-1578070181910-f1e514afdd08?w=400&q=80',
    videoUrl: '',
    duration: 30,
    credits: 800,
    hasSound: true,
    characterCount: 2,
    isPopular: true,
    characters: [
      { id: 'c1', thumbnailUrl: 'https://i.pravatar.cc/80?img=1' },
      { id: 'c2', thumbnailUrl: 'https://i.pravatar.cc/80?img=2' },
      { id: 'c3', thumbnailUrl: 'https://i.pravatar.cc/80?img=3' },
      { id: 'c4', thumbnailUrl: 'https://i.pravatar.cc/80?img=4' },
      { id: 'c5', thumbnailUrl: 'https://i.pravatar.cc/80?img=5' },
    ],
  },
  {
    id: 'pn-2',
    title: 'Neon Anime',
    category: 'Popular Now',
    thumbnailUrl: 'https://images.unsplash.com/photo-1614028674026-a65e31bfd27c?w=400&q=80',
    videoUrl: '',
    duration: 25,
    credits: 700,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'pn-3',
    title: 'Couples Dance',
    category: 'Popular Now',
    thumbnailUrl: 'https://images.unsplash.com/photo-1504609813442-a8924e83f76e?w=400&q=80',
    videoUrl: '',
    duration: 28,
    credits: 750,
    hasSound: true,
    characterCount: 2,
    isPopular: true,
  },

  // ─── All Eyes On You ────────────────────────────────────────────────────────
  {
    id: 'ae-1',
    title: 'Diva Walk',
    category: 'All Eyes On You',
    thumbnailUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&q=80',
    videoUrl: '',
    duration: 20,
    credits: 700,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'ae-2',
    title: 'Red Carpet',
    category: 'All Eyes On You',
    thumbnailUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&q=80',
    videoUrl: '',
    duration: 25,
    credits: 750,
    hasSound: true,
    characterCount: 1,
    isPopular: true,
  },
  {
    id: 'ae-3',
    title: 'Spotlight',
    category: 'All Eyes On You',
    thumbnailUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&q=80',
    videoUrl: '',
    duration: 22,
    credits: 720,
    hasSound: true,
    characterCount: 1,
  },

  // ─── Cartoon ────────────────────────────────────────────────────────────────
  {
    id: 'ct-1',
    title: 'Anime Hero',
    category: 'Cartoon',
    thumbnailUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=400&q=80',
    videoUrl: '',
    duration: 20,
    credits: 600,
    hasSound: true,
    characterCount: 1,
    isTrending: true,
  },
  {
    id: 'ct-2',
    title: 'Pixel Dance',
    category: 'Cartoon',
    thumbnailUrl: 'https://images.unsplash.com/photo-1617791160505-6f00504e3519?w=400&q=80',
    videoUrl: '',
    duration: 18,
    credits: 550,
    hasSound: true,
    characterCount: 1,
  },
  {
    id: 'ct-3',
    title: 'Toon Style',
    category: 'Cartoon',
    thumbnailUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    videoUrl: '',
    duration: 22,
    credits: 580,
    hasSound: true,
    characterCount: 2,
    isTrending: true,
  },
];

export const TEMPLATE_CATEGORIES = [
  'Featured',
  'Trend Videos',
  'Viral Dance',
  'Kids Dance',
  'Popular Now',
  'All Eyes On You',
  'Cartoon',
];

export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'weekly_3000',
    name: 'Diamond Unlimited',
    credits: 3000,
    priceDisplay: '₺449,99',
    period: 'Hafta',
    trialDays: 3,
    features: [
      'Unlimited AI video generation',
      '3000 credits per week',
      'Priority processing',
      'HD video quality',
      'No watermark',
    ],
  },
];

export const getTemplateById = (id: string): Template | undefined =>
  MOCK_TEMPLATES.find((t) => t.id === id);

export const getTemplatesByCategory = (category: string): Template[] =>
  MOCK_TEMPLATES.filter((t) => t.category === category);
